version: '3.0'

services:
  telegram_bot:
      build: ./telegram_bot/
      restart: always
      depends_on:
        mysql:
          condition: service_healthy
      volumes:
        - data_volume:/var/log/myapp  # Mount point for logging inside the telegram_bot container

  mysql:
      image: mysql:latest
      restart: always
      environment:
          MYSQL_DATABASE: my_db
          MYSQL_ROOT_PASSWORD: 'root'
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 3s
          retries: 20
      ports:
          - '3306:3306'
      volumes:
          - data_volume:/var/lib/mysql  # Persistent storage for MySQL
          
  flyway:
    image: flyway/flyway:latest
    volumes:
      - "./MySQL/migrations:/flyway/sql"
    command: -url=jdbc:mysql://mysql:3306/my_db?allowPublicKeyRetrieval=true -user=root -password=root migrate
    depends_on:
        mysql:
            condition: service_healthy

volumes:
  data_volume:
    driver: local
